version: "3.7"

services:
  nn_falcon_api:
    image: namgivu/falcon_start
    container_name: nn_falcon_start  # nn aka namgivu shorthand

    ports:
      - "${PORT:-6000}:6000"
    volumes:
      - .:/app

    restart: always

    command: # multi-line command ref. https://stackoverflow.com/a/55406543/248616
      - /bin/bash
      - -c
      - |
        cd /app
          pipenv --rm; pipenv sync
          ./bin/run-api.sh
