version: "3.7"

services:
  nn_falcon_api:
    image: namgivu/falcon_start
    container_name: nn_falcon_start  # nn aka namgivu shorthand

    volumes:
      - .:/app

    # keep container running ref. https://stackoverflow.com/a/48732671/248616
    command: tail -F /dev/null
